FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        software-properties-common \
        build-essential \
        vim \
    && pip install opencv-python-headless==4.8.1.78 scipy==1.12.0 matplotlib==3.8.2

WORKDIR /app